# Generated by Django 2.2.12 on 2022-04-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enroll', models.CharField(max_length=45)),
                ('rollno', models.CharField(max_length=45)),
                ('name', models.TextField()),
                ('eti1', models.IntegerField()),
                ('eti2', models.IntegerField()),
                ('mgt1', models.IntegerField()),
                ('mgt2', models.IntegerField()),
                ('wbp1', models.IntegerField()),
                ('wbp2', models.IntegerField()),
                ('pwp1', models.IntegerField()),
                ('pwp2', models.IntegerField()),
                ('mad1', models.IntegerField()),
                ('mad2', models.IntegerField()),
            ],
        ),
    ]
